"""empty message

Revision ID: 59a72a8e651e
Revises: 6b2fd242cf11
Create Date: 2023-01-16 11:09:46.373617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59a72a8e651e'
down_revision = '6b2fd242cf11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(), nullable=False))
        batch_op.create_unique_constraint('uq_token', ['token'])
        batch_op.create_unique_constraint('uq_userid', ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_userid', type_='unique')
        batch_op.drop_constraint('uq_token', type_='unique')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
