"""empty message

Revision ID: 6b2fd242cf11
Revises: 75cb3c23e152
Create Date: 2023-01-16 11:03:41.121341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b2fd242cf11'
down_revision = '75cb3c23e152'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(), nullable=False))
        batch_op.create_unique_constraint('uq_name', ['user_id'])
        batch_op.create_unique_constraint(None, ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint('uq_name', type_='unique')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
