"""empty message

Revision ID: 799284337f50
Revises: 09f9a7eaa23b
Create Date: 2023-01-16 10:23:15.837874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '799284337f50'
down_revision = '09f9a7eaa23b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(), nullable=False))

    # ### end Alembic commands ###
